import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;


public class InputTest {
    private Input i;
    private AdventureContainer roster;
    private ArrayList<ArrayList<String>> inputInfo;
    private int n;
    
    @Before
    public void setup(){
        n = 500;
        i = new Input();
        roster = new AdventureContainer();
        inputInfo = new ArrayList<>();
        inputInfo.add(new ArrayList<>(Arrays.asList( "aa" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "aa" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "aa" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "aa" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "aa" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "aa" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "dM0eSxZkyoyXG6Zg5y0(3WEvKa,mVuvko8MxlDXE8uN6xsdOQ_3,Uxy)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "3WEvKa" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "3WEvKa" , "zPsn" , "Sword" , "150" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "zPsn" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "3WEvKa" , "1" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "R9sYGQ" , "HealSpell" , "11" , "269" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "WLcKT" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "WLcKT" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "Uxy(92WlI5WA01bYj8a2nCXRtWlg)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "f_q8r2MNSxPOfoe4VBM4" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "Qlo" , "AttackSpell" , "15" , "163" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "z_8K3gd2mQNIcIlEt2z923p" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "MXea_Cc2" , "AttackSpell" , "10" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "MXea_Cc2" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "HQrB" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "HQrB" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "_TEaDUx" , "HealSpell" , "15" , "94" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "qFv6i9_" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "c51hZfMTM2_o5h8MKIgn" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "Uxy" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "f_q8r2MNSxPOfoe4VBM4" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "dM0eSxZkyoyXG6Zg5y0" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "dM0eSxZkyoyXG6Zg5y0" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "dM0eSxZkyoyXG6Zg5y0" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "Uxy" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "aOXN3XvM97R7_qxyr" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "Uxy" , "nRt3kP" , "Sword" , "150" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "Uxy" , "nRt3kP" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "Uxy" , "1" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "8RzX02mFUUj833VePZ" , "HpBottle" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "8RzX02mFUUj833VePZ" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "8RzX02mFUUj833VePZ" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "8RzX02mFUUj833VePZ" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "WLcKT" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "WLcKT" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "UCL4tenyeYCodhq" , "HealSpell" , "5" , "130" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "MXea_Cc2" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkNutu" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "nRt3kP" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "N1LqGjN" , "DefBottle" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "N1LqGjN" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "N1LqGjN" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "StZw" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "JkQk" , "AttackSpell" , "3" , "110" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "lwQo8L2kIFb0f7ULIy" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "f_q8r2MNSxPOfoe4VBM4" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "c51hZfMTM2_o5h8MKIgn" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkNutu" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "yxP2F7iE8PgSMxwUM5FZN" , "AttackSpell" , "10" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "yxP2F7iE8PgSMxwUM5FZN" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "kyU_nCBedjV" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "lwQo8L2kIFb0f7ULIy" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "z_8K3gd2mQNIcIlEt2z923p" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "mVmqLshEqN" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "QRNjUe" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "dM0eSxZkyoyXG6Zg5y0(mVuvko8MxlDXE8uN6xsdOQ_3,Uxy,92WlI5WA01bYj8a2nCXRtWlg)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "Uxy" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "F_nQ0cnwoHwCF9" , "Sword" , "150" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "F_nQ0cnwoHwCF9" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "1" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "WTxaHix3P5JijOEnm4I" , "HealSpell" , "12" , "18" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "dlkCz5R_1GwnN" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "mcy2pGm0FpFdCuh9NlRIVa" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "dlkCz5R_1GwnN" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "WX0y2K97oHFLCNQN" , "AttackSpell" , "10" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "WX0y2K97oHFLCNQN" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "lmRMTr" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "15TYnDJR3VGgb8toksW0" , "HealSpell" , "1" , "88" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "MXea_Cc2" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "N1LqGjN" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "OxyJYomRMv" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "nDfGQxZqo_20YiI9kjmdlV2" , "HealSpell" , "8" , "294" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "sm7JnsQseBaDWgKvGkSxaHx" , "AtkBottle" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "sm7JnsQseBaDWgKvGkSxaHx" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "sm7JnsQseBaDWgKvGkSxaHx" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "tBPYCH" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "Qlo" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "WTxaHix3P5JijOEnm4I" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "1we" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "msiAqV5DHI3qnk" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "qFv6i9_" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "3WEvKa(dM0eSxZkyoyXG6Zg5y0)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "KtBQW6EiYs4mYV" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "InI4_x" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "muiMQyF" , "AttackSpell" , "17" , "264" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "iArhfVZQimVLI33lF4qNu" , "HealSpell" , "21" , "53" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "sm7JnsQseBaDWgKvGkSxaHx" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "lwQo8L2kIFb0f7ULIy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "mcy2pGm0FpFdCuh9NlRIVa" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "sm7JnsQseBaDWgKvGkSxaHx" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "OxyJYomRMv" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "StZw" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "R9sYGQ" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "QRNjUe" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "tBPYCH" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "haiWLI1" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "lmRMTr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "mcy2pGm0FpFdCuh9NlRIVa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "R6RKLOct_4QRY" , "AttackSpell" , "21" , "95" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "f_7Jb" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "_1Xb" , "HealSpell" , "20" , "181" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "InI4_x" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "f_7Jb" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "3WEvKa" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "mVmqLshEqN" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UCL4tenyeYCodhq" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "f_7Jb" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "oqFUbM_jm7YzIG6CVWx6AnRw" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "zPsn" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "Fyxb8xE42Sd9U_Zt8" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "9MGYNGc7qLQ09" , "HealSpell" , "1" , "66" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "iArhfVZQimVLI33lF4qNu" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "1we" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UCL4tenyeYCodhq" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "n1O" , "HealSpell" , "21" , "146" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "oqFUbM_jm7YzIG6CVWx6AnRw" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "msiAqV5DHI3qnk" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "Fr_XGcVb6Nn6H" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkhI4uaSZ" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "jJZUUs9nJmJLROc8te" , "HealSpell" , "10" , "7" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "OxyJYomRMv" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "3WEvKa" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "muiMQyF" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "rHbljFi6qGN3SgfZH" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "4yZymHzDqgaZlk2tGrGG" , "AttackSpell" , "12" , "30" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "YjEzaKDzt" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "yxP2F7iE8PgSMxwUM5FZN" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "Fyxb8xE42Sd9U_Zt8" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "_1Xb" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "zDqo6Xp7z0yo1aqo" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "AnwHQQAWn1zJsjxe" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "xrUrDTW" , "HealSpell" , "3" , "254" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "YjEzaKDzt" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "haiWLI1" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "UAPZ8z8BAH5ou_plwba" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "StZw" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "nDfGQxZqo_20YiI9kjmdlV2" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "yxP2F7iE8PgSMxwUM5FZN" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "kyU_nCBedjV" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "tBPYCH" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "UCL4tenyeYCodhq" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "VgO" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "StZw" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "_keKInPvMXe3OKCl" , "HealSpell" , "8" , "158" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "JkQk" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "2dWHmnjpoHz_Bou" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkhI4uaSZ" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "tBPYCH" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkhI4uaSZ" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "aOXN3XvM97R7_qxyr" , "YOcs_J1suWL30Yumd0jY" , "ManaBottle" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "aOXN3XvM97R7_qxyr" , "YOcs_J1suWL30Yumd0jY" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "YOcs_J1suWL30Yumd0jY" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "Y8DW8ag_wPsmF2QPsF1vL8U" , "HealSpell" , "25" , "240" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "RvkTXBgQ9_8_ZBh_Ih4TWRe7" , "AttackSpell" , "21" , "4" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "4vr3vJ3CRg0AIptZya1v" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "0RgP9Z" , "AttackSpell" , "13" , "164" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "aOXN3XvM97R7_qxyr(Uxy)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "rHbljFi6qGN3SgfZH" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "8y1nlkmB6oKINII" , "HealSpell" , "6" , "244" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "_TEaDUx" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "KtBQW6EiYs4mYV" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "sigCqxEaLRvWmIM6mINhZ6bZ" , "AttackSpell" , "1" , "262" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "jJZUUs9nJmJLROc8te" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "JkQk" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "4vr3vJ3CRg0AIptZya1v" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "vM_qZVPC0WXNARP" , "AttackSpell" , "30" , "140" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "6zdxyL2b" , "HealSpell" , "5" , "120" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "25yC84YEMCkw6ahZGx9L" , "AttackSpell" , "3" , "193" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "Du4Ag7kg0tHagh_WM9J" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "YjEzaKDzt" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "8y1nlkmB6oKINII" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "lW57cG" , "HealSpell" , "27" , "17" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "nDfGQxZqo_20YiI9kjmdlV2" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "VgO" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "6zdxyL2b" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "zDqo6Xp7z0yo1aqo" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "zDqo6Xp7z0yo1aqo" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "OxyJYomRMv" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "KA06QCBGpROOID" , "HealSpell" , "18" , "230" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "Jwd" , "HpBottle" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "Jwd" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "Jwd" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "c3eaDS" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "xrUrDTW" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "aOXN3XvM97R7_qxyr" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "yxP2F7iE8PgSMxwUM5FZN" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "B0RCtqj3y_UmJOe_cTW" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "c3eaDS" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "IM0uqQZFfjK" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "zDqo6Xp7z0yo1aqo" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "dM0eSxZkyoyXG6Zg5y0(Uxy)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "IhioOI8mmW" , "HealSpell" , "6" , "33" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkhI4uaSZ" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "S5lqh3hyyGkeNCpu4zR_OB" , "HealSpell" , "27" , "83" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "YjEzaKDzt" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "9sdgUwoer7teMeoE_i" , "AttackSpell" , "11" , "110" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "4yZymHzDqgaZlk2tGrGG" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "c6HYtDvH5iH1utDKyu" , "HealSpell" , "10" , "7" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "YjEzaKDzt" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "iu6LMjcQ029gh" , "AttackSpell" , "4" , "37" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "QUlzehE" , "AttackSpell" , "9" , "112" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "n5O2yLRFLcDcDOfW" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "4vr3vJ3CRg0AIptZya1v" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "rHbljFi6qGN3SgfZH" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "au6KYnPVqroJqRjqxkJOQwY" , "HealSpell" , "27" , "77" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "jJZUUs9nJmJLROc8te" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "pDyHAfZnm4bjZBmZ3Yx" , "AttackSpell" , "4" , "296" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "3WEvKa" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "Du4Ag7kg0tHagh_WM9J" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "B0RCtqj3y_UmJOe_cTW" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "n5O2yLRFLcDcDOfW" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "MXea_Cc2" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "acBQy" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "BmAC_7vP_Fkr8HpPtClvUi" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "WTxaHix3P5JijOEnm4I" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "9sdgUwoer7teMeoE_i" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "OxyJYomRMv" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "9zY7" , "AttackSpell" , "6" , "31" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "6vvu5qO" , "AttackSpell" , "23" , "8" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "0RgP9Z" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "9sdgUwoer7teMeoE_i" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "acBQy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "G_d_vd243U1i9Ob0" , "AttackSpell" , "25" , "85" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "92WlI5WA01bYj8a2nCXRtWlg(dM0eSxZkyoyXG6Zg5y0)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "fyd6" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "92WlI5WA01bYj8a2nCXRtWlg" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "dCAMkjfZMtwgTmHxEr" , "AttackSpell" , "26" , "275" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "qskkUkvXJMI4J" , "AttackSpell" , "8" , "153" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "s9egrA5Q68gjEkFky7LwOQ3o" , "AttackSpell" , "19" , "8" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "1A19oGLOA8LqADriEOzmzfl" , "AttackSpell" , "5" , "156" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "c3eaDS" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "PieDJmXZ9i" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "c3eaDS" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "4KRclOxHT" , "AttackSpell" , "4" , "36" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "7ugMopX" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "XAO" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "_coPFzAwf8Wrm71L2mxjP" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "Gmi8u18wFxE83" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "UEMazzDWqMnyS6" , "AttackSpell" , "16" , "173" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "xjuYgmspo9onwNm" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkhI4uaSZ" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "UPefO9CC64Pf30Ni2YQT" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "92WlI5WA01bYj8a2nCXRtWlg(3WEvKa)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "9WmxskVdh6ZEZr" , "AttackSpell" , "30" , "188" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "mVuvko8MxlDXE8uN6xsdOQ_3(92WlI5WA01bYj8a2nCXRtWlg)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "x3smbGPdzIdQmhl2" , "DefBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "7HmSidkB9xpEA9" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "C0iIg8VVvdy45QxQGZn" , "AttackSpell" , "21" , "274" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "YbKd_gl9" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "aRKUB" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "mGiAC_YZX5BP__74" , "Magicbook" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "RvkTXBgQ9_8_ZBh_Ih4TWRe7" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "IQ_43Yh6J7jIidLvMj035" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "CdZskjN" , "HealSpell" , "13" , "260" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "XAO" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "0RgP9Z" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "1A19oGLOA8LqADriEOzmzfl" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "IQ_43Yh6J7jIidLvMj035" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "aOXN3XvM97R7_qxyr" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "Mxq5anU" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "WX0y2K97oHFLCNQN" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "92WlI5WA01bYj8a2nCXRtWlg" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "7ugMopX" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "WeK_X" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "TbL6Q" , "HealSpell" , "24" , "137" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "BmAC_7vP_Fkr8HpPtClvUi" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "_c3MPaJjtf" , "AttackSpell" , "17" , "20" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "uav" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "TbL6Q" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "R6RKLOct_4QRY" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "prs" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "JkQk" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "WeK_X" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "YbKd_gl9" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "xjuYgmspo9onwNm" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "Dxf4A_3sOR" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "86moSe5Lp4uwEVGFeE8g1N" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "Uxy" , "dAze1j4DpGNK7A8" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "AnwHQQAWn1zJsjxe" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "UPefO9CC64Pf30Ni2YQT" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "M0ym" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "Gmi8u18wFxE83" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "0U4ubT" , "HealSpell" , "16" , "82" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "NKm2" , "HealSpell" , "21" , "157" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "9WmxskVdh6ZEZr" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "WO8xSYfezOk7JOQU" , "Sword" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "JkQk" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "fs_Xhz62zVYTo5Jh2D3" , "HealSpell" , "13" , "278" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "WTxaHix3P5JijOEnm4I" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "Mxq5anU" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "42ptqJX" , "AttackSpell" , "14" , "93" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "xfYIKgXQsSjw0" , "AttackSpell" , "9" , "215" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "3WEvKa" , "Wjy4BZxrU2jQcr0LuV" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "92WlI5WA01bYj8a2nCXRtWlg" , "sH0" , "AttackSpell" , "16" , "56" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "Wjy4BZxrU2jQcr0LuV" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "aOXN3XvM97R7_qxyr" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "dM0eSxZkyoyXG6Zg5y0(3WEvKa,aOXN3XvM97R7_qxyr,92WlI5WA01bYj8a2nCXRtWlg)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "3WEvKa" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "aOXN3XvM97R7_qxyr" , "1" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "3WEvKa" , "1yHON_n1ORUR1ZoIE0j_" , "Sword" , "150" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "1yHON_n1ORUR1ZoIE0j_" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "fight" , "3WEvKa" , "1" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "M0ym" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "r_M0Cy" , "ManaBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "_coPFzAwf8Wrm71L2mxjP" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "dAze1j4DpGNK7A8" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "M0ym" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "9zY7" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "6zdxyL2b" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "dM0eSxZkyoyXG6Zg5y0" , "hHpbxFgaJB" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "c6HYtDvH5iH1utDKyu" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "sigCqxEaLRvWmIM6mINhZ6bZ" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "JY_BaonPLNEU" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "Ujd5N2jT" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "Ujd5N2jT" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "Ujd5N2jT" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "fyd6" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "IM0uqQZFfjK" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "R9sYGQ" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "92WlI5WA01bYj8a2nCXRtWlg" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "gkhI4uaSZ" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "CZla" , "AttackSpell" , "15" , "87" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "t_wbVFFA_NoQ32C2hiw" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "EVXumL8HOktcmHG71" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "EVXumL8HOktcmHG71" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "EVXumL8HOktcmHG71" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "sH0" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "Ujd5N2jT" , "92WlI5WA01bYj8a2nCXRtWlg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "Mxq5anU" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "y9srJ8u6sHY" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "aOXN3XvM97R7_qxyr" , "Ah9p53NS_WlvyyyPe" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "aOXN3XvM97R7_qxyr" , "Ah9p53NS_WlvyyyPe" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "Ah9p53NS_WlvyyyPe" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "9dhRdR" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "QpkemcIYlxogAnqdlryI" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "QpkemcIYlxogAnqdlryI" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "QpkemcIYlxogAnqdlryI" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "joXWSAF0G7IkO0x41" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "Uxy" , "getd9L489y0adMb7F" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "Uxy" , "getd9L489y0adMb7F" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "getd9L489y0adMb7F" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "K1ox08KvqBWEEFOZZtgUO" , "AtkBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "_TEaDUx" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "K1ox08KvqBWEEFOZZtgUO" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "zwiBjpHiVsDyPno0IWsKI2z" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "BYMUvlVYsh797n4LDVV" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "BYMUvlVYsh797n4LDVV" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "BYMUvlVYsh797n4LDVV" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "cYPSqE7SlxzZ9r7" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "iMtHtCiu7YJhWCHn1H" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "iMtHtCiu7YJhWCHn1H" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "iMtHtCiu7YJhWCHn1H" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "cKfU3jUBEWocDr" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "nOg" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "nOg" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "nOg" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "QpkemcIYlxogAnqdlryI" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "CvNSAMc" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "2fBGA2MsFWXqfODTPabn7I" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "2fBGA2MsFWXqfODTPabn7I" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "2fBGA2MsFWXqfODTPabn7I" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "7mwHBlRzsICoK5owVZgaGG6w" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "aOXN3XvM97R7_qxyr" , "t_WYVv" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "aOXN3XvM97R7_qxyr" , "t_WYVv" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "t_WYVv" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "x3smbGPdzIdQmhl2" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "dM0eSxZkyoyXG6Zg5y0(aOXN3XvM97R7_qxyr)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "aRKUB" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "EVXumL8HOktcmHG71" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "3WEvKa" , "U7ujgB" , "AttackSpell" , "8" , "292" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "Uxy" , "getd9L489y0adMb7F" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "BYMUvlVYsh797n4LDVV" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "Ruu1snL84cS_cE" , "ManaBottle" , "50" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "Ruu1snL84cS_cE" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "Ruu1snL84cS_cE" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "_coPFzAwf8Wrm71L2mxjP" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "FSEnZv8P51H" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "Sy5iLkqNzjD1fb5s" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "JTJ6dn" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "JTJ6dn" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "JTJ6dn" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "3WEvKa" , "IM0uqQZFfjK" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "klpVOqYd41SJHyqE0" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "gAbTTcQzcQld" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "gAbTTcQzcQld" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "gAbTTcQzcQld" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "9jkN2spofPHm5dhtx" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "Uxy" , "kvTUsGvcgMbtaArtDFOIs" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "Uxy" , "kvTUsGvcgMbtaArtDFOIs" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "kvTUsGvcgMbtaArtDFOIs" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "MGbnSqci8wEz3TA4n0mWPyW" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "uy_2Ze6C" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "uy_2Ze6C" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "uy_2Ze6C" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "_43X_e" , "HealSpell" , "28" , "135" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "dM0eSxZkyoyXG6Zg5y0" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "aOXN3XvM97R7_qxyr" , "jECcBUWbUxycAgYac" , "Armour" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "aOXN3XvM97R7_qxyr" , "tQh41a3sCKUrPm" , "AttackSpell" , "20" , "30" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "_keKInPvMXe3OKCl" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "M0ym" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "bi" , "92WlI5WA01bYj8a2nCXRtWlg" , "aYpTK4YhsxUYq" , "HpBottle" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "Kq4O18C" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "z4KLB7G" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "z4KLB7G" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "z4KLB7G" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "rr" , "92WlI5WA01bYj8a2nCXRtWlg" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "Ah9p53NS_WlvyyyPe" , "dM0eSxZkyoyXG6Zg5y0" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "aOXN3XvM97R7_qxyr" , "t_WYVv" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "xW0XV0Ph" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "Uxy" , "rsootuUq_PAJKgMtocIGi" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "Uxy" , "rsootuUq_PAJKgMtocIGi" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "rsootuUq_PAJKgMtocIGi" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "dM0eSxZkyoyXG6Zg5y0" , "0WVO5hCziVouPa" , "HealSpell" , "12" , "43" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "rBwMB_1q36roacDQQoqZx7L" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "6sPtgUj3LEA" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "6sPtgUj3LEA" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "6sPtgUj3LEA" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "1aKQs_9wzwsCSWfNSMAeho" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "r8qN" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "r8qN" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "r8qN" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "dMl0nMsR" , "HealSpell" , "25" , "168" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "aYpTK4YhsxUYq" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "RXqB46IRoER8niRDPtrqd" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "OKjgTo" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "OKjgTo" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "OKjgTo" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "r8qN" , "aOXN3XvM97R7_qxyr" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ls" , "Uxy" , "U4c1LAT72k3BZYx_c8Cf" , "HealSpell" , "30" , "189" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ar" , "aOXN3XvM97R7_qxyr" , "3WEvKa" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "VLFrDL9gBGpdfanp10pSNti" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "rOiVztK91E6u_ea" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "rOiVztK91E6u_ea" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "rOiVztK91E6u_ea" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "pBoxux8MzeXVX" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "Uxy" , "y4kFdFzdKKyzIEbxYlMUk2" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "Uxy" , "y4kFdFzdKKyzIEbxYlMUk2" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "Uxy" , "y4kFdFzdKKyzIEbxYlMUk2" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ri" , "92WlI5WA01bYj8a2nCXRtWlg" , "gAbTTcQzcQld" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "WEZ" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "_R0Iq2yaKqjrFNVTb7rgZO" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "_R0Iq2yaKqjrFNVTb7rgZO" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "92WlI5WA01bYj8a2nCXRtWlg" , "_R0Iq2yaKqjrFNVTb7rgZO" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "D5U" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "3WEvKa" , "1pglZvm_AZdTSK4_N6vQM9" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "3WEvKa" , "1pglZvm_AZdTSK4_N6vQM9" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "3WEvKa" , "1pglZvm_AZdTSK4_N6vQM9" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "F2uD0siA" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "6n5nNG6uzRCGLaY" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "6n5nNG6uzRCGLaY" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "6n5nNG6uzRCGLaY" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "aOXN3XvM97R7_qxyr" , "CdZskjN" , "Uxy" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "lr" , "Uxy(92WlI5WA01bYj8a2nCXRtWlg)" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "ULI1BX3qp2ew6fPEGAOMlW" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "dM0eSxZkyoyXG6Zg5y0" , "YSqSAIXfjwMgkMzvTbIoHNPk" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "dM0eSxZkyoyXG6Zg5y0" , "YSqSAIXfjwMgkMzvTbIoHNPk" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "use" , "dM0eSxZkyoyXG6Zg5y0" , "YSqSAIXfjwMgkMzvTbIoHNPk" , "mVuvko8MxlDXE8uN6xsdOQ_3" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ae" , "mVuvko8MxlDXE8uN6xsdOQ_3" , "3NfuTbDZDqhkLehw" , "Armour" , "100" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ab" , "92WlI5WA01bYj8a2nCXRtWlg" , "0Js7KRl8FD_" , "HpBottle" , "1000" )));
        inputInfo.add(new ArrayList<>(Arrays.asList( "ti" , "92WlI5WA01bYj8a2nCXRtWlg" , "0Js7KRl8FD_" )));

    }

    @Test
    public void exe() {
        i.exe(inputInfo,n,roster);
    }
}